name: Build & Release APK - Ayo Taaruf

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ''
          channel: 'stable'
          cache: true

      - name: Accept Android SDK Licenses
        run: |
          yes | flutter doctor --android-licenses || true
          yes | sdkmanager --licenses || true

      - name: Install Dependencies
        run: flutter pub get

      - name: Format Check
        run: dart format .

      - name: Analyze Code
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk