name: Build & Release APK - Ayo Taaruf

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ''
          channel: 'stable'
          cache: true

      - name: Accept Android SDK Licenses
        run: |
          yes | flutter doctor --android-licenses || true
          yes | sdkmanager --licenses || true

      - name: Install Dependencies
        run: flutter pub get

      - name: Format Check
        run: dart format .

      - name: Analyze Code
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release

      - name: Extract SHA-1 from APK
        run: |
          echo "================================="
          echo "🔐 APK Certificate SHA-1 Fingerprint"
          echo "================================="
          keytool -printcert -jarfile build/app/outputs/flutter-apk/app-release.apk | grep -E "(SHA1|SHA256)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Release v1.0.${{ github.run_number }}
          body: |
            APK hasil build otomatis.
            - Commit: ${{ github.sha }}
            - Branch: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
